---@meta


---@type integer
LE_EXPANSION_WRATH_OF_THE_LICH_KING = 2

---@type integer
LE_EXPANSION_LEVEL_CURRENT = 99

---@type integer
WOW_PROJECT_WRATH_CLASSIC = 11

LE_MOUNT_JOURNAL_FILTER_COLLECTED = -1
LE_MOUNT_JOURNAL_FILTER_NOT_COLLECTED = -1
LE_MOUNT_JOURNAL_FILTER_UNUSABLE = -1

GameTooltip = {

}

--#region Global Strings

OKAY = "Okay"
KEY_BINDINGS = ""
KEY_BUTTON3 = ""
KEY_BACKSPACE = ""
KEY_SPACE = ""
KEY_DELETE = ""
KEY_HOME = ""
KEY_END = ""
KEY_INSERT = ""
KEY_PAGEUP = ""
KEY_PAGEDOWN = ""
KEY_DOWN = ""
KEY_UP = ""
KEY_LEFT = ""
KEY_RIGHT = ""
INVTYPE_TRINKET  = ""
--#endregion Global Strings
